# Generated by Django 3.0.6 on 2020-05-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20200522_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='rickurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
