# Generated by Django 3.0.6 on 2020-05-22 14:40

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_rickurl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rickurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortner.validators.validate_url, shortner.validators.validate_dot_com]),
        ),
    ]
