# Generated by Django 3.0.6 on 2020-05-22 14:41

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_auto_20200522_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rickurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortner.validators.validate_url]),
        ),
    ]
