# Generated by Django 3.0.6 on 2020-07-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0005_auto_20200522_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rickurl',
            name='active',
        ),
        migrations.RemoveField(
            model_name='rickurl',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='rickurl',
            name='updated',
        ),
    ]
